# Generated by Django 2.2.6 on 2019-11-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_post_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_category',
        ),
    ]
